prefix :        <http://esipfed.org/essi-lod/ontology#> 
prefix dc:      <http://purl.org/dc/terms/> 
prefix geo:     <http://www.w3.org/2003/01/geo/wgs84_pos#> 
prefix foaf:    <http://xmlns.com/foaf/0.1/> 
prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> 
prefix tw:      <http://tw.rpi.edu/schema/> 
prefix owl:     <http://www.w3.org/2002/07/owl#> 
prefix xsd:     <http://www.w3.org/2001/XMLSchema#> 
prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix swrc:    <http://swrc.ontoware.org/ontology#> 
prefix skos:    <http://www.w3.org/2004/02/skos/core#> 
prefix swc:     <http://data.semanticweb.org/ns/swc/ontology#> 
select ?k1 ?p1 ?k2 ?p2 (count(?abstract) as ?count) where {
 ?abstract swc:hasTopic ?k1 .
 OPTIONAL { ?k1 skos:broadMatch ?p1 . }
 ?abstract swc:hasTopic ?k2 .
 OPTIONAL { ?k2 skos:broadMatch ?p2 . }
 FILTER (?k1 != ?k2)
}
group by ?k1 ?k2 ?p1 ?p2
order by desc(?count)