prefix :        <http://esipfed.org/essi-lod/ontology#>
prefix dc:      <http://purl.org/dc/terms/>
prefix geo:     <http://www.w3.org/2003/01/geo/wgs84_pos#>
prefix foaf:    <http://xmlns.com/foaf/0.1/>
prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
prefix tw:      <http://tw.rpi.edu/schema/>
prefix owl:     <http://www.w3.org/2002/07/owl#>
prefix xsd:     <http://www.w3.org/2001/XMLSchema#>
prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix swrc:    <http://swrc.ontoware.org/ontology#>
prefix skos:    <http://www.w3.org/2004/02/skos/core#>
prefix swc:     <http://data.semanticweb.org/ns/swc/ontology#>
select ?s1 ?s2 (count(?person) as ?count) where {
 ?abstract1 swc:relatedToEvent ?session1 .
 ?abstract1 tw:hasAgentWithRole ?role1 .
 ?person tw:hasRole ?role1 .
 ?session1 swc:isSubEventOf ?section1 .
 ?section1 dc:identifier ?s1 .
 ?abstract2 swc:relatedToEvent ?session2 .
 ?abstract2 tw:hasAgentWithRole ?role2 .
 ?person tw:hasRole ?role2 .
 ?session2 swc:isSubEventOf ?section2 .
 ?section2 dc:identifier ?s2 .	      
 FILTER	   (?s1 < ?s2)
}